### ISSUE TITLE
More flexible yes_no Property Detection

### ISSUE THREAD

**Issue by ec-m** [Roboy/ravestate#107]
Right now, only single words like `yes`, `yeah` or `nope` are recognized as `yes` or respectively `no`. However, the `prop_yesno` should also be filled if one says longer phrases like `yes that sounds good` or `no thank you`.

**Comment by josephbirkner** [comment]
Thanks for reporting! Do you want to add it to your current sprint? @emlozin Do you fancy picking this one up?

**Comment by emlozin** [comment]
@josephbirkner Can do :)

**Comment by josephbirkner** [comment]
Thanks!
