### ISSUE TITLE
Allow splitting of module into separate files

### ISSUE THREAD

**Issue by ec-m** [Roboy/ravestate#111]
Right now it is not possible to conveniently split a module into separate files. If properties are declared outside `with`-blocks, then we might run into problems of unknown properties to states since the states remember the properties' paths as strings. If a property is declared in the `with`-block of a file `a` then this property cannot be used in other files. It would be helpful if splitting a module in this way could work in order to improve the software architecture of bigger modules.

**Comment by josephbirkner** [comment]
Implemented with #136

**Comment by ec-m** [comment]
Awesome 🎉
