### ISSUE TITLE
prop_yesno should return False instead of negative value

### ISSUE THREAD

**Issue by ec-m** [Roboy/ravestate#132]
The following screenshot shows that `prop_yesno` holds `-2` instead of `False` when `no` is inserted. This is not what I would expect (and also not what was probably intended).

<img width="889" alt="Screenshot 2019-08-16 at 19 18 14" src="https://user-images.githubusercontent.com/10234559/63186054-c1f31100-c05b-11e9-831f-1c0f2a413718.png">

**Comment by josephbirkner** [comment]
Resolved with #133
