### ISSUE TITLE
Native horizontal scrolling

### ISSUE THREAD

**Issue by josephbirkner** [Roboy/ravestate#138]
It would be very useful to be able to scroll horizontally in the UI with natural scrolling gestures, such as two-finger pan or scroll-wheel. This could be achieved by wrapping the SVG area in a div that has `overflow-x` set to `scroll`. However, we would need to implement dynamic resizing of the SVG area based on its content.

**Comment by josephbirkner** [comment]
@nbasargin thoughts?

**Comment by nbasargin** [comment]
It's on my list. Right now, we move the SVG elements in the graph with transform property which gives nice transitions for free. The size of the graph needs to stay fixed for the automatic resizing. Wrapping the graph into two divs, one with a scrollbar and the other with the correct size set should allow scrolling.

**Comment by nbasargin** [comment]
PR's up: #142 :rocket:
