### ISSUE TITLE
Pimp up GenQA

### ISSUE THREAD

**Issue by NeginsCode** [Roboy/ravestate#28]
Handling HTTP get request errors in ravestate_genqa.
The drqa_module() handles the request.

**Comment by josephbirkner** [comment]
- [ ] Triggered by `nlp:input-is-question`
- [ ] Configurable sanity threshold for docscore/answer-score
- [ ] Return state.Resign() if now answer or "insane" answer
- [ ] Connectivity check on startup (`<url>/uup` -> ` !!! Your DrQA server does not seem to be running, GenQA will not work. !!!`)
