### ISSUE TITLE
Introduce symbols for property/signal names

### ISSUE THREAD

**Issue by josephbirkner** [Roboy/ravestate#40]
Currently, the lack of symbols for property/signal names has 3 drawbacks:
1. unused import warnings for dependencies
2. typos in property paths lead to errors
3. forgetting dependencies

Therefore, the following set of ravestate API changes should be introduced:
- [x] §0 Properties may be constructed like `my_prop = PropertyBase(...)` in a `with Module(...)` clause, module scope is assigned automatically. Dependencies may then use `my_prop`.
- [x] §1 `Signal` can be constructed in `with Module ...` clause, module scope will be set automatically. Signal may be used as parameter `signal=my_signal` in state declaration
- [x] §2 Referring to signals by name should become illegal. The `s(...)` function will be removed. Refer either by exported module variable, or by the respective Property/State APIs.
- [x] §3 Setting Signal constraint properties like `min_age`, `max_age`, `detached`, will be moved from constructor parameters to chainable function calls: `my_signal.min_age(30).detached()`. Each function call returns a copy of the signal with the respective member value change.
- [x] §4 Properties will be referrable by symbols. The context's push/pop/__setitem__/__getitem__ functions will be changed accordingly.
- [x] §5  It should be prevented, that developers call a property's read/write function directly. For this purpose, context should always adopt copies of the respective property objects. The originals will be untouched. An exception to this rule is generally made for child properties, since they mark an advanced use-case where properties are generally created dynamically, and usually accessed through their path anyway.
- [x] §6 The `PropertyBase` class will be renamed to `Property`.

**Comment by josephbirkner** [comment]
@Toseban thoughts?

**Comment by Toseban** [comment]
I like it very much :ok_hand:
Would definitely make the code cleaner and less error prone to typos.

**Comment by josephbirkner** [comment]
Implemented with #86
