### ISSUE TITLE
Multi-processing for TelegramIO

### ISSUE THREAD

**Issue by josephbirkner** [Roboy/ravestate#42]
Currently, parallel telegram conversations always share a context (mutiparty use-case is assumed) Alternately, TelegramIO should offer the possibility to fork ravestate for multiple convos, such that the conversations are separated.

This is going to require the introduction of an additional head-less IO module, e.g. process bridge.

**Comment by Toseban** [comment]
implemented in https://github.com/Roboy/ravestate/pull/55
