### ISSUE TITLE
Completed signals must not introduce new causal group into conjunction

### ISSUE THREAD

**Issue by Toseban** [Roboy/ravestate#57]
There is currently no active engagement when ravestate_telegramio is active because the telegram_run state is always running

**Comment by josephbirkner** [comment]
Maybe we should add `:startup` to our boring signal whitelist?

**Comment by josephbirkner** [comment]
After more investigation, probably an issue with completed signals acquiring from different causal groups. Fix almost ready.

**Comment by josephbirkner** [comment]
Resolved with 348585e7cf9efd9c2c6411701aee8dc92b97fb8e
