### ISSUE TITLE
Exception in Telegram Bot

### ISSUE THREAD

**Issue by Toseban** [Roboy/ravestate#63]
![telegram_bot_error_intent](https://user-images.githubusercontent.com/3384323/53264145-3c5d5c80-36db-11e9-92c5-069b6867c939.png)

The exception occurred while starting a new conversation with "Hey" with the telegram bot.
The bot did not answer anything, but after sending another message, everything worked fine.
The bug was not reproducible.

**Comment by josephbirkner** [comment]
May be related to #57

**Comment by josephbirkner** [comment]
Resolved with 348585e7cf9efd9c2c6411701aee8dc92b97fb8e
